### ISSUE TITLE
watchテーブル作成

### ISSUE THREAD

**Issue by Ikko-T** [T-Tsujii/gyakuten_clone_group29#50]
watchテーブルをデータベースに反映させるために`rails db:migrate`
だけど重複エラー：

```
rails db:migrate
== 20201030093321 AlterMovies: migrating ======================================
-- add_column(:movies, :genre, :string)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "genre" of relation "movies" already exists
/Users/ikko/yanbaru_code/gyakuten_clone_group29/db/migrate/20201030093321_alter_movies.rb:3:in `change'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/rails:9:in `<top (required)>'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "genre" of relation "movies" already exists
/Users/ikko/yanbaru_code/gyakuten_clone_group29/db/migrate/20201030093321_alter_movies.rb:3:in `change'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/rails:9:in `<top (required)>'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::DuplicateColumn: ERROR:  column "genre" of relation "movies" already exists
/Users/ikko/yanbaru_code/gyakuten_clone_group29/db/migrate/20201030093321_alter_movies.rb:3:in `change'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/rails:9:in `<top (required)>'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by Ikko-T** [comment]
- https://dev.to/neshaz/join-table-in-rails-23b5

**Comment by Ikko-T** [comment]
>「視聴済!」のデータが重複しないように，[user_id, movie_id] の組の一意性（同じ組を複数保存できない）制約を入れる

⏬


```
add_index :watches, [:user_id, :movie_id, unique: true]
```
書き方と説明の意味をよく理解してないが、とりあえず進める。
あとで確認要

**Comment by Ikko-T** [comment]
下記エラー文から
```
PG::DuplicateColumn: ERROR: 
```
下記サイト参考に

- https://k-koh.hatenablog.com/entry/2020/05/29/174420

`rails db:reset`を実行

別のエラー発生：
```
ikko@ikkonoAir gyakuten_clone_group29 % rails db:reset
PG::ObjectInUse: ERROR:  database "gyakuten_clone_group29_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
Couldn't drop database 'gyakuten_clone_group29_development'
rails aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "gyakuten_clone_group29_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/rails:9:in `<top (required)>'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::ObjectInUse: ERROR:  database "gyakuten_clone_group29_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/rails:9:in `<top (required)>'
/Users/ikko/yanbaru_code/gyakuten_clone_group29/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

```

**Comment by Ikko-T** [comment]
- https://dev.to/neshaz/join-table-in-rails-23b5

**Comment by Ikko-T** [comment]
>サーバーだけでなく，Posticoも起動してはいけないのですが，終了させていますか。念のため
kill -9 $(lsof -i tcp:3000 -t)
を実行し，Railsサーバーを全て落とせばリセットできるでしょう。

上記を実行し
```
rails db:migrate:reset
```
データベースを一度リセット。
それからrakeタスクコマンドを使用し再度データを書き込む
